#!/bin/sh
branch_name=$(git symbolic-ref HEAD | sed 's!refs/heads/!!')

if [ "$branch_name" = "main" ] || [ "$branch_name" = "master" ] || [ "$branch_name" = "dev" ]; then
  echo "You are trying to push to the '$branch_name' branch directly, which is not allowed."
  exit 1
fi

echo "Running lint..."
if ! npm run lint; then
  echo "Lint failed"
  exit 1
fi

echo "Running build..."
if ! npm run build; then
  echo "Build failed"
  exit 1
fi

echo "Pre-push checks passed"