import { DimensionDto } from '@common/dto/dimension.dto';
import { ResourceNotFoundException } from '@common/exceptions/custom-exceptions';
import { PrismaService } from '@modules/prisma/prisma.service';
import { Injectable, BadRequestException } from '@nestjs/common';
import { Prisma, Project, Tag, ProjProvLinkRole } from '@prisma/client';

type ProvocationWithProjects = Prisma.ProvocationGetPayload<{
  include: {
    projects: {
      include: {
        project: true;
      };
    };
  };
}>;

import { CreateProjectFromProvocationDto } from './dto/create-project-from-provocation.dto';
import { CreateProjectDto } from './dto/create-project.dto';
import { CreateProvocationDto } from './dto/create-provocation.dto';
import { CreateTagDto } from './dto/create-tag.dto';
import { ProjectUserDto } from './dto/project-user.dto';
import { ProjectDto } from './dto/project.dto';
import { ProvocationDto } from './dto/provocation.dto';
import { TagDto } from './dto/tag.dto';
import { UpdateProjectDto } from './dto/update-project.dto';
import { UserRoleResponseDto } from './dto/user-role-response.dto';
import { DEFAULT_DIMENSIONS, DEFAULT_SCALES } from './resources/default-values';
import { ProjectConfiguration } from './types/project-configuration.type';
import { TimelineGraph, ProjectNode, Edge } from './types/timeline.type';

@Injectable()
export class ProjectRepository {
  constructor(private prisma: PrismaService) {}

  private parseToProjectConfiguration(
    config: Prisma.JsonValue,
  ): ProjectConfiguration {
    const parsedConfig = config as unknown as ProjectConfiguration;

    return {
      dimensions: parsedConfig.dimensions.map((dim) => ({
        name: dim.name,
        color: dim.color,
      })),
      scales: parsedConfig.scales,
    };
  }

  private parseToJson(config: ProjectConfiguration): Prisma.InputJsonValue {
    return {
      dimensions: config.dimensions.map((dim) => ({
        name: dim.name,
        color: dim.color,
      })),
      scales: config.scales,
    };
  }

  private parseToProjectDto(project: Project): ProjectDto {
    return {
      id: project.id,
      name: project.name,
      description: project.description ?? undefined,
      configuration: this.parseToProjectConfiguration(project.configuration),
      createdAt: project.createdAt,
      organizationId: project.organizationId,
    };
  }

  private parseToTagDto(tag: Tag): TagDto {
    return {
      name: tag.name,
      color: tag.color,
    } as TagDto;
  }

  private parseToProvocationDto(
    provocation: ProvocationWithProjects,
  ): ProvocationDto {
    const content = provocation.content as {
      title?: string;
      description?: string;
    } | null;

    const originProjects = provocation.projects.filter(
      (project) => project.role === ProjProvLinkRole.ORIGIN,
    );
    const parsedOriginProjects = originProjects.map((project) =>
      this.parseToProjectDto(project.project),
    );

    const provocationDto = {
      id: provocation.id,
      question: provocation.question,
      title: content?.title,
      description: content?.description,
      parentProvocationId: provocation.parentProvocationId ?? undefined,
      createdAt: provocation.createdAt,
      updatedAt: provocation.updatedAt,
      projects: parsedOriginProjects,
    };
    return provocationDto;
  }

  // find wich project generated this provocation
  private async findGeneratedProjectByProvocation(
    tx: Prisma.TransactionClient,
    provocationId: string,
  ): Promise<Project | null> {
    const generatedProjectLink = await tx.projectProvocationLink.findFirst({
      where: {
        provocationId,
        role: ProjProvLinkRole.GENERATED,
      },
      include: {
        project: true,
      },
    });

    return generatedProjectLink?.project || null;
  }

  // TODO: when we have method to find initial project, replace `${parentProject.name}: ...` for `${initialProject.name}: ...`
  private buildProvocationProjectName(
    generatedProject: Project | null,
    provocationQuestion: string,
    provocationContent: { title?: string; description?: string } | null,
    providedName?: string,
  ): string {
    const provocationTitle = provocationContent?.title || provocationQuestion;

    if (generatedProject) {
      return `${generatedProject.name}: ${provocationTitle}`;
    } else {
      if (!providedName) {
        throw new BadRequestException(
          'Project name is required when the provocation was not generated by any project.',
        );
      }
      return providedName;
    }
  }

  private buildProvocationProjectDescription(
    provocationQuestion: string,
    provocationContent: { title?: string; description?: string } | null,
  ): string {
    return provocationContent?.description || provocationQuestion;
  }

  private validateProvocationProjectValuesMatchParent(
    generatedProject: Project,
    organizationId?: string,
    dimensions?: DimensionDto[],
    scales?: string[],
  ): void {
    const parentConfig = this.parseToProjectConfiguration(
      generatedProject.configuration,
    );

    // Validate organizationId matches parent if provided
    if (organizationId && organizationId !== generatedProject.organizationId) {
      throw new BadRequestException(
        `Organization ID must match parent project's organization (${generatedProject.organizationId}) or be omitted to inherit it.`,
      );
    }

    // Validate dimensions match parent if provided
    if (dimensions && dimensions.length > 0) {
      const dimensionsMatch =
        dimensions.length === parentConfig.dimensions.length &&
        dimensions.every(
          (dim, index) =>
            dim.name === parentConfig.dimensions[index]?.name &&
            dim.color === parentConfig.dimensions[index]?.color,
        );

      if (!dimensionsMatch) {
        throw new BadRequestException(
          'Dimensions must match parent project dimensions or be omitted to inherit them.',
        );
      }
    }

    // Validate scales match parent if provided
    if (scales && scales.length > 0) {
      const scalesMatch =
        scales.length === parentConfig.scales.length &&
        scales.every((scale, index) => scale === parentConfig.scales[index]);

      if (!scalesMatch) {
        throw new BadRequestException(
          'Scales must match parent project scales or be omitted to inherit them.',
        );
      }
    }
  }

  private setProvocationProjectConfigurationValues(
    parentProject: Project | null,
    providedDimensions?: DimensionDto[],
    providedScales?: string[],
    providedOrganizationId?: string,
  ): {
    dimensions: DimensionDto[];
    scales: string[];
    organizationId: string;
  } {
    let dimensions: DimensionDto[];
    let scales: string[];
    let organizationId: string;

    // Set dimensions: use provided, inherit from parent, or use defaults
    if (!providedDimensions || providedDimensions.length === 0) {
      if (parentProject) {
        const parentConfig = this.parseToProjectConfiguration(
          parentProject.configuration,
        );
        dimensions = parentConfig.dimensions;
      } else {
        // No parent project, use defaults
        dimensions = DEFAULT_DIMENSIONS;
      }
    } else {
      dimensions = providedDimensions;
    }

    // Set scales: use provided, inherit from parent, or use defaults
    if (!providedScales || providedScales.length === 0) {
      if (parentProject) {
        const parentConfig = this.parseToProjectConfiguration(
          parentProject.configuration,
        );
        scales = parentConfig.scales;
      } else {
        // No parent project, use defaults
        scales = DEFAULT_SCALES;
      }
    } else {
      scales = providedScales;
    }

    // Set organizationId: use provided, inherit from parent, or throw error
    if (!providedOrganizationId) {
      if (parentProject) {
        organizationId = parentProject.organizationId;
      } else {
        throw new ResourceNotFoundException(
          'Organization',
          'undefined',
          'Organization ID is required when no parent project exists',
        );
      }
    } else {
      organizationId = providedOrganizationId;
    }

    return { dimensions, scales, organizationId };
  }

  async create(
    createProjectDto: CreateProjectDto,
    userId: string,
    roleId: string,
  ): Promise<ProjectDto> {
    return this.prisma.$transaction(async (tx) => {
      const project = await tx.project.create({
        data: {
          name: createProjectDto.name,
          description: createProjectDto.description,
          configuration: this.parseToJson({
            dimensions: createProjectDto.dimensions!,
            scales: createProjectDto.scales!,
          }),
          organizationId: createProjectDto.organizationId,
        },
      });

      await tx.userProjectRole.create({
        data: {
          userId,
          projectId: project.id,
          roleId: roleId,
        },
      });

      return this.parseToProjectDto(project);
    });
  }

  async createFromProvocation(
    createProjectFromProvocationDto: CreateProjectFromProvocationDto,
    userId: string,
    roleId: string,
  ): Promise<ProjectDto> {
    return this.prisma.$transaction(async (tx) => {
      const provocation = await tx.provocation.findFirst({
        where: {
          id: createProjectFromProvocationDto.fromProvocationId,
          isActive: true,
        },
      });

      if (!provocation) {
        throw new ResourceNotFoundException(
          'Provocation',
          createProjectFromProvocationDto.fromProvocationId,
        );
      }

      const provocationContent = provocation.content as {
        title?: string;
        description?: string;
      } | null;

      const parentProject = await this.findGeneratedProjectByProvocation(
        tx,
        createProjectFromProvocationDto.fromProvocationId,
      );

      const projectName = this.buildProvocationProjectName(
        parentProject,
        provocation.question,
        provocationContent,
        createProjectFromProvocationDto.name,
      );
      const projectDescription = this.buildProvocationProjectDescription(
        provocation.question,
        provocationContent,
      );

      // Validate provided values match parent if parent exists
      if (parentProject) {
        this.validateProvocationProjectValuesMatchParent(
          parentProject,
          createProjectFromProvocationDto.organizationId,
          createProjectFromProvocationDto.dimensions,
          createProjectFromProvocationDto.scales,
        );
      }

      // Set configuration values: use provided, inherit from parent, or use defaults
      const { dimensions, scales, organizationId } =
        this.setProvocationProjectConfigurationValues(
          parentProject,
          createProjectFromProvocationDto.dimensions,
          createProjectFromProvocationDto.scales,
          createProjectFromProvocationDto.organizationId,
        );

      // Create the project with data from the provocation
      const project = await tx.project.create({
        data: {
          name: projectName,
          description: projectDescription,
          configuration: this.parseToJson({
            dimensions,
            scales,
          }),
          organizationId,
          parentProjectId: parentProject?.id,
        },
      });

      // Create the provocation link
      await tx.projectProvocationLink.create({
        data: {
          projectId: project.id,
          provocationId: createProjectFromProvocationDto.fromProvocationId,
          role: ProjProvLinkRole.ORIGIN,
        },
      });

      // Create the user role relationship
      await tx.userProjectRole.create({
        data: {
          userId,
          projectId: project.id,
          roleId: roleId,
        },
      });

      return this.parseToProjectDto(project);
    });
  }

  async findAllPaginated(
    skip: number,
    take: number,
    userId: string,
  ): Promise<[ProjectDto[], number]> {
    const whereClause = {
      isActive: true,
      userRoles: {
        some: {
          userId: userId,
        },
      },
    };
    const [projects, total] = await this.prisma.$transaction([
      this.prisma.project.findMany({
        where: whereClause,
        skip,
        take,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.project.count({
        where: whereClause,
      }),
    ]);

    return [projects.map((project) => this.parseToProjectDto(project)), total];
  }

  async findOne(id: string): Promise<ProjectDto | null> {
    const project = await this.prisma.project.findFirst({
      where: {
        id,
        isActive: true,
      },
    });

    if (!project) {
      return null;
    }

    return this.parseToProjectDto(project);
  }

  async remove(id: string): Promise<ProjectDto> {
    const project = await this.prisma.project.update({
      where: { id },
      data: {
        isActive: false,
        deletedAt: new Date(),
      },
    });

    return this.parseToProjectDto(project);
  }

  async removeWithCascade(id: string): Promise<ProjectDto> {
    return this.prisma.$transaction(async (tx) => {
      // 1. Soft delete all mandalas in the project
      await tx.mandala.updateMany({
        where: {
          projectId: id,
          isActive: true,
        },
        data: {
          isActive: false,
          deletedAt: new Date(),
        },
      });

      // 2. Soft delete the project itself
      const project = await tx.project.update({
        where: { id },
        data: {
          isActive: false,
          deletedAt: new Date(),
        },
      });

      return this.parseToProjectDto(project);
    });
  }

  async update(
    id: string,
    updateProjectDto: UpdateProjectDto,
  ): Promise<ProjectDto> {
    const updateData: {
      name?: string;
      description?: string;
      organizationId?: string;
      configuration?: Prisma.InputJsonValue;
    } = {};

    if (updateProjectDto.name !== undefined) {
      updateData.name = updateProjectDto.name;
    }

    if (updateProjectDto.description !== undefined) {
      updateData.description = updateProjectDto.description;
    }

    if (updateProjectDto.organizationId !== undefined) {
      updateData.organizationId = updateProjectDto.organizationId;
    }

    if (
      updateProjectDto.dimensions !== undefined ||
      updateProjectDto.scales !== undefined
    ) {
      const currentProject = await this.prisma.project.findUnique({
        where: { id },
        select: { configuration: true },
      });

      if (!currentProject) {
        throw new Error(`Project with id ${id} not found`);
      }

      const currentConfig = this.parseToProjectConfiguration(
        currentProject.configuration,
      );

      updateData.configuration = this.parseToJson({
        dimensions: updateProjectDto.dimensions ?? currentConfig.dimensions,
        scales: updateProjectDto.scales ?? currentConfig.scales,
      });
    }

    const project = await this.prisma.project.update({
      where: { id },
      data: updateData,
    });

    return this.parseToProjectDto(project);
  }

  async getProjectTags(projectId: string): Promise<TagDto[]> {
    return this.prisma.tag.findMany({
      where: {
        projectId,
        isActive: true,
      },
    });
  }

  async createTag(projectId: string, dto: CreateTagDto): Promise<TagDto> {
    return this.prisma.$transaction(async (tx) => {
      const existingSoftDeletedTag = await tx.tag.findFirst({
        where: {
          name: dto.name,
          projectId,
          isActive: false,
        },
      });

      if (existingSoftDeletedTag) {
        return tx.tag.update({
          where: { id: existingSoftDeletedTag.id },
          data: {
            isActive: true,
            deletedAt: null,
            color: dto.color,
          },
        });
      }

      return tx.tag.create({
        data: {
          name: dto.name,
          color: dto.color,
          projectId,
        },
      });
    });
  }

  async findProjectTag(projectId: string, tagId: string): Promise<Tag | null> {
    return this.prisma.tag.findFirst({
      where: {
        id: tagId,
        projectId: projectId,
        isActive: true,
      },
    });
  }

  async removeTag(projectId: string, tagId: string): Promise<TagDto> {
    const deletedTag = await this.prisma.tag.update({
      where: {
        id: tagId,
        projectId: projectId,
      },
      data: {
        isActive: false,
        deletedAt: new Date(),
      },
    });

    return this.parseToTagDto(deletedTag);
  }

  async updateUserRole(
    projectId: string,
    userId: string,
    roleId: string,
  ): Promise<UserRoleResponseDto> {
    // Verificar que el usuario existe en el proyecto
    const existingUserRole = await this.prisma.userProjectRole.findUnique({
      where: {
        userId_projectId: {
          userId,
          projectId,
        },
      },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
          },
        },
        role: true,
      },
    });

    if (!existingUserRole) {
      throw new ResourceNotFoundException('User', userId, 'en el proyecto');
    }

    // Actualizar el rol del usuario
    const updatedUserRole = await this.prisma.userProjectRole.update({
      where: {
        userId_projectId: {
          userId,
          projectId,
        },
      },
      data: {
        roleId,
      },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
          },
        },
        role: true,
      },
    });

    return {
      userId: updatedUserRole.userId,
      projectId: updatedUserRole.projectId,
      role: updatedUserRole.role.name,
      user: updatedUserRole.user,
    };
  }

  async getProjectUsers(projectId: string): Promise<ProjectUserDto[]> {
    const userRoles = await this.prisma.userProjectRole.findMany({
      where: {
        projectId,
      },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
            is_active: true,
          },
        },
        role: {
          select: {
            name: true,
          },
        },
      },
      orderBy: {
        user: {
          username: 'asc',
        },
      },
    });

    return userRoles.map((userRole) => ({
      id: userRole.user.id,
      username: userRole.user.username,
      email: userRole.user.email,
      role: userRole.role.name,
      isActive: userRole.user.is_active,
    }));
  }

  async removeUserFromProject(
    projectId: string,
    userId: string,
  ): Promise<ProjectUserDto> {
    // Verificar que el usuario existe en el proyecto
    const existingUserRole = await this.prisma.userProjectRole.findUnique({
      where: {
        userId_projectId: {
          userId,
          projectId,
        },
      },
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
            is_active: true,
          },
        },
        role: {
          select: {
            name: true,
          },
        },
      },
    });

    if (!existingUserRole) {
      throw new ResourceNotFoundException('User', userId, 'en el proyecto');
    }

    // Eliminar la relación usuario-proyecto
    await this.prisma.userProjectRole.delete({
      where: {
        userId_projectId: {
          userId,
          projectId,
        },
      },
    });

    return {
      id: existingUserRole.user.id,
      username: existingUserRole.user.username,
      email: existingUserRole.user.email,
      role: existingUserRole.role.name,
      isActive: existingUserRole.user.is_active,
    };
  }

  async findAllByOrganizationPaginated(
    organizationId: string,
    skip: number,
    take: number,
  ): Promise<[ProjectDto[], number]> {
    const whereClause: Prisma.ProjectWhereInput = {
      isActive: true,
      organizationId,
    };

    const [projects, total] = await this.prisma.$transaction([
      this.prisma.project.findMany({
        where: whereClause,
        skip,
        take,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.project.count({ where: whereClause }),
    ]);

    return [projects.map((project) => this.parseToProjectDto(project)), total];
  }

  async getUserRole(
    projectId: string,
    userId: string,
  ): Promise<{ id: string; name: string } | null> {
    const projectUser = await this.prisma.userProjectRole.findUnique({
      where: { userId_projectId: { userId, projectId } },
      include: { role: true },
    });
    return projectUser?.role
      ? { id: projectUser.role.id, name: projectUser.role.name }
      : null;
  }

  async countOwners(projectId: string): Promise<number> {
    return this.prisma.userProjectRole.count({
      where: { projectId, role: { name: 'owner' } },
    });
  }

  async autoAssignOrganizationMembers(
    projectId: string,
    organizationId: string,
  ): Promise<void> {
    const orgMembers = await this.prisma.userOrganizationRole.findMany({
      where: { organizationId },
      include: { role: true },
    });

    for (const member of orgMembers) {
      await this.prisma.userProjectRole.upsert({
        where: {
          userId_projectId: {
            userId: member.userId,
            projectId: projectId,
          },
        },
        update: {
          roleId: member.roleId,
        },
        create: {
          userId: member.userId,
          projectId: projectId,
          roleId: member.roleId,
        },
      });
    }
  }

  async findProjectsByUserAndOrganization(
    userId: string,
    organizationId: string,
    skip: number,
    take: number,
  ): Promise<[ProjectDto[], number]> {
    const whereClause: Prisma.ProjectWhereInput = {
      isActive: true,
      organizationId,
      userRoles: {
        some: {
          userId,
        },
      },
    };

    const [projects, total] = await this.prisma.$transaction([
      this.prisma.project.findMany({
        where: whereClause,
        skip,
        take,
        orderBy: { createdAt: 'desc' },
        include: {
          organization: true,
          userRoles: {
            include: {
              role: true,
              user: true,
            },
          },
        },
      }),
      this.prisma.project.count({ where: whereClause }),
    ]);

    return [projects.map((p) => this.parseToProjectDto(p)), total];
  }

  async createProvocation(
    projectId: string,
    createProvocationDto: CreateProvocationDto,
  ): Promise<ProvocationDto> {
    const existingOriginLink =
      await this.prisma.projectProvocationLink.findFirst({
        where: {
          projectId: projectId,
          role: ProjProvLinkRole.ORIGIN,
        },
      });

    const provocation = await this.prisma.provocation.create({
      data: {
        question: createProvocationDto.question,
        content: {
          title: createProvocationDto.title,
          description: createProvocationDto.description,
        },
        parentProvocationId: existingOriginLink?.provocationId,
        projects: {
          create: {
            projectId: projectId,
            role: ProjProvLinkRole.GENERATED,
          },
        },
      },
      include: {
        projects: {
          include: {
            project: true,
          },
        },
      },
    });

    return this.parseToProvocationDto(provocation);
  }

  async findAllProvocationsByProjectId(
    projectId: string,
  ): Promise<ProvocationDto[]> {
    const provocationLinks = await this.prisma.projectProvocationLink.findMany({
      where: {
        projectId,
        role: ProjProvLinkRole.GENERATED,
        provocation: {
          isActive: true,
        },
      },
      include: {
        provocation: {
          include: {
            projects: {
              include: {
                project: true,
              },
            },
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    return provocationLinks.map((link) =>
      this.parseToProvocationDto(link.provocation),
    );
  }

  private searchProjectDepths(
    projects: Array<{
      id: string;
      parentProjectId: string | null;
    }>,
  ): Map<string, number> {
    const projectById = new Map(projects.map((p) => [p.id, p]));
    const depths = new Map<string, number>();

    // Find roots and compute depths via BFS
    const roots = projects.filter(
      (p) => !p.parentProjectId || !projectById.has(p.parentProjectId),
    );
    const queue = roots.map((r) => ({ id: r.id, depth: 0 }));

    while (queue.length > 0) {
      const { id, depth } = queue.shift()!;
      if (depths.has(id)) continue;

      depths.set(id, depth);

      // Add children to queue
      projects
        .filter((p) => p.parentProjectId === id)
        .forEach((child) => queue.push({ id: child.id, depth: depth + 1 }));
    }

    return depths;
  }

  private createProjectParentEdges(
    projects: Array<{
      id: string;
      createdAt: Date;
      parentProjectId: string | null;
    }>,
  ): Edge[] {
    const projectById = new Map(projects.map((p) => [p.id, p]));

    return projects
      .filter((p) => p.parentProjectId && projectById.has(p.parentProjectId))
      .map((p) => ({
        from: p.parentProjectId!,
        to: p.id,
        type: 'PROJECT_PARENT' as const,
        createdAt: p.createdAt.toISOString(),
      }));
  }

  async getTimelineGraph(
    organizationId: string,
    highlightProjectId?: string,
  ): Promise<TimelineGraph> {
    const projects = await this.prisma.project.findMany({
      where: {
        organizationId,
        isActive: true,
      },
      select: {
        id: true,
        name: true,
        description: true,
        createdAt: true,
        parentProjectId: true,
      },
      orderBy: { createdAt: 'asc' },
    });

    const projectNodes: ProjectNode[] = projects.map((p) => ({
      id: p.id,
      type: 'project' as const,
      name: p.name,
      description: p.description || undefined,
      createdAt: p.createdAt.toISOString(),
      parentId: p.parentProjectId,
      label: p.name,
      isHighlighted: p.id === highlightProjectId,
    }));

    const depths = this.searchProjectDepths(projects);

    projectNodes.forEach((node) => {
      node.depth = depths.get(node.id) || 0;
    });

    const projectParentEdges = this.createProjectParentEdges(projects);

    const edges: Edge[] = [...projectParentEdges];

    const allNodes = [...projectNodes];
    allNodes.sort(
      (a, b) =>
        new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
    );

    return {
      nodes: allNodes,
      edges,
    };
  }
}
